name: Releases
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: git checkout
        uses: actions/checkout@v1
      - name: Run tests
        run: go test ./...
      - name: Build
        run: ./build.sh
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "fizz_buzz_*"
          token: ${{ secrets.GITHUB_TOKEN }}
