name: Tests
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: git checkout
        uses: actions/checkout@v1
      #      - name: Run lint
      #          run: go test ./...
      - name: Run unit tests
        run: go test ./...

